teamhanko/hanko

session/session.go

The cookie config was added as a function parameter to `session.NewManager`, but was never used.

add config to sessionManager

---

cmd/jwt/create.go
config/config.go
server/public_router.go
session/session.go
session/session_test.go

This PR adds a session lifespan config. It also uses the sameSite config for the cookie. This PR alters the config structure a little bit, to make it clearer, that the cookie config only applies to the session.

feat: add session lifespan config & refatoring

---

session/session.go

Set the session cookie path to root "/" so it can be used on all pages of a website.

set session cookie to root path

---

docs/spec/api.yaml
handler/user.go
handler/user_test.go
server/public_router.go

adds the endpoint `/me` which redirects to `users/:id` when the session is valid.

feat: add endpoint which redirects to current user resource

---

example/main.go
example/middleware/cache_control.go

The browser should not cache the responses from the example, because if you go to `/secured` directly, then the browser might show the cached version of it, although the session cookie was removed or the session was expired.

don't cache pages for the example in the browser

---

backend/handler/user.go
backend/handler/user_test.go

Currently every logged in user can get user info for every user from the api (`/users/:id`) when he knows the id of a user. So we have broken authorization for this endpoint. This PR fixes this problem.

get user object only for himself

---

README.md
deploy/docker-compose/quickstart.yaml

Use a new docker compose spec version, so that the services start in the correct order and wait for specific services they depend on

chore: fix docker compose that components start in correct order

---

backend/persistence/migrations/20220405154240_create_webauthn_credentials.up.fizz

Change the database column type for the webauthn public keys, because currently the default length which `fizz` assigns is 255, which is too short for some public keys (like Windows Hello ones). This PR changes the column type to `text`, so that which doesn't have a explicit max length.

fix database column type to store longer webauthn public keys

---

backend/handler/passcode.go
backend/handler/passcode_test.go

Currently passcodes can be tried indefinitely, but the user should only be able to try them 3 times. This is because we always return `errors` except for the success case, but when we return errors in a transaction, the transaction gets rolled back and the number of tries are not saved. 
This PR fixes it, but might not be the best solution. But it will work for now.

passcode max attempts

---

backend/handler/webauthn.go
backend/handler/webauthn_test.go
hanko-js/src/lib/HankoClient.ts

* When something client related fails during WebAuthn authentication the UI always shows the "Invalid WebAuthn credentials error" - some cases have resulted in a "Technical error".
* Updates the API status codes for /webauthn/login/finalize. If the request was correct (correct types/syntactically valid values), but for example the user was not found, an unauthorized error is returned.

83 example not friendly ux when trying to sign in before registering

---

backend/handler/user.go
backend/handler/user_admin.go
backend/handler/user_test.go

This PR always transforms the emails to lowercase, so that `john.doe@example.com` will be the same as `JOHN.DOE@example.com`.

use always lowercase emails

---

backend/config/config.go

JSON struct tags for public config attributes were removed in 7d4f120.
The 'Password.Enabled' attribute is now serialized with an uppercase first letter.
Aside from being inconsistent (the parent `Password` attribute in the
`PublicConfig` struct has a proper JSON struct tag with an uncapitalized
first letter) the hanko-js web component can't handle this: it results
in login flows disregarding passwords and falling back to a passwordless
flow even though they might be enabled in the backend config.

fix(backend): re-add json struct tags for public config attributes

---

backend/dto/intern/WebauthnCredential.go

Sometimes a client sends a transport list with an empty string:
```
transports: ["internal", ""]
```
The backend should ignore those values.

fix: ignore transport with empty string

---

backend/config/config.go
backend/docs/Config.md
backend/handler/passcode.go
backend/handler/passcode_test.go
backend/handler/password.go
backend/handler/password_test.go
backend/handler/user.go
backend/handler/user_test.go
backend/handler/webauthn.go
backend/handler/webauthn_test.go
backend/server/public_router.go
backend/session/session.go
docs/spec/api.yaml
hanko-js/package-lock.json
hanko-js/package.json
hanko-js/src/lib/HankoClient.ts

* Added a new config parameter `EnableAuthToken` to the session config. This causes the API to issue a JWT via the `X-Auth-Token` header. 
* The HankoClient (.ts) will notice and create a client-side cookie containing the value of `X-Auth-Token`
Sidenotes:
* In the different handlers, due to the introduction of the new config parameter "EnableAuthToken", I needed to access the session config. Since all configs are passed separately as parameters into the handler constructors, I would have had to pass a third config in some cases. But all configs are members of the `config.Config{}` type. So instead of creating another parameter, I changed the handlers to accept `config.Config{}`. This way there is no need to update the router and the test files again, when a handler needs to access …

feat: handle auth-token header and create cross domain cookies

---

backend/handler/webauthn.go

This PR fixes logins on android. Currently android does not support discoverable credentials, so the `userHandle` property in an authenticator assertion is missing. 
Before this PR we relied on the `userHandle` (which basically is the userId) every time, but now we only rely on it, when it is a discoverable login.

fix: fix webauthn login when userHandle is empty

---

example/main.go

Renderer is already assigned a few lines earlier

refactor(example): remove redundant template renderer assignment

---

README.md

Under licenses, internal link AGPL-3.0 returned a 404 error. the broken internal link was updated.

Found Broken Link under Licenses

---

example/public/assets/css/index.css
hanko-js/src/ui/components/InputPasscodeDigit.tsx
hanko-js/src/ui/pages/LoginEmail.tsx

- Minor padding changes for example app
- Comply with preact 10.10.0 property requirements (see failing tests for https://github.com/teamhanko/hanko/pull/132)
- added autocorrect = off to username input to prevent autocorrection in Safari:
https://user-images.githubusercontent.com/20115649/182851687-37b9872a-e84e-41e5-a1cd-e960776be41a.mov

small changes to input properties and example css

---

backend/crypto/jwk/generator_rsa.go
docs/spec/api.yaml

also updates jwk related content in the api spec (external doc links to rfcs, removing non-public attributes from jwk schema)

feat(jwk): make explicit public jwks are used for verifying signatures

---

LICENSE
README.md

chore: add License note for frontend-sdk

---

docs/docs/guides/backend.mdx

How to test that the example works:
1. Download [this](https://github.com/teamhanko/hanko/files/9566841/test2.zip) and decompress in a location of your choice
2. In the directory run `npm install` then `DEBUG=express,jwks HANKO_API_URL=http://localhost:8000 node server.js`
3. Start a hanko backend available on port `8000`
4. Create a user or use an existing user
5. Create a JWT (e.g. through https://github.com/teamhanko/hanko/blob/main/backend/cmd/jwt/create.go)
6. Make requests:
```bash
curl http://localhost:4001/me -H "Authorization: Bearer <JWT>"
curl http://localhost:4001/me --cookie "hanko=<JWT>" 
```

docs: add js backend guide example

---

docs/docusaurus.config.js

Add plausible analytics to the docs
https://plausible.io/docs/docusaurus-integration

docs: add plausible analytics

---

e2e/README.md

Fix a broken link in the end to end test readme.

docs: fix broken link in e2e readme

---

backend/persistence/audit_log_persister.go
backend/persistence/jwk_persister.go
backend/persistence/passcode_persister.go
backend/persistence/password_credential_persister.go
backend/persistence/user_persister.go
backend/persistence/webauthn_credential_persister.go
backend/persistence/webauthn_session_data_persister.go

Check if the error returned by pop contains a wrapped `sql.ErrNoRows` error 
Fixes #334 
Use the [`errors.Is`](https://pkg.go.dev/errors#Is) function to check if the returned error contains a wrapped `sql.ErrNoRows`.
See #334

fix: check wrapped error for sql.ErrNoRows

---

deploy/docker-compose/quickstart.debug.yaml

Make compose debug file work with new frontend lib dir structure (introduced in a37219a0)

fix: make compose debug file work with new frontend lib dir structure

---

deploy/docker-compose/quickstart.debug.yaml

Set the correct frontend SDK URL environment variable in the compose debug file.

fix: set correct frontend sdk url env var in compose debug file

---

frontend/elements/README.md

Fix links to base customization css example file and customization preview image source URL in elements readme.

docs: fix links in elements readme

---

CONTRIBUTING.md

Allow chore prefix in contribution commit guidelines.

docs: allow chore prefix in contribution commit guidelines

---

backend/Dockerfile
backend/Dockerfile.debug
backend/handler/audit_log.go
backend/handler/user_admin.go
backend/handler/user_admin_test.go
backend/pagination/header.go
backend/pagination/header_test.go
backend/persistence/audit_log_persister.go
backend/persistence/user_persister.go
backend/test/audit_log_persister.go
backend/test/user_persister.go
docs/static/spec/admin.yaml

Adds the `Link` and `X-Total-Count` header to list audit logs and list users. The `X-Total-Count` header returns the total count of the requested resource. The `Link` header returns urls which can be used for pagination. 
E.g. there are 155 registered users and the user list is requested with `?page=5&per_page=10`, then
- the `X-Total-Count` header returns 155
- the `Link` header returns `<http://localhost:8001/users?page=1&per_page=10>; rel="first",<http://localhost:8001/users?page=16&per_page=10>; rel="last",<http://localhost:8001/users?page=6&per_page=10>; rel="next",<http://localhost:8001/users?page=4&per_page=10>; rel="prev"`
To test this just use the admin audit_log and admin users api and look into the returned headers.
https://docs.github.com/en/rest/guides/traversing-with-paginati …

Add total count & link header for pagination

---

.github/workflows/docker-publish.yml
backend/Dockerfile
frontend/Dockerfile
frontend/frontend-sdk/Dockerfile
quickstart/Dockerfile

I am doing development on an Apple Silicon Mac and doing deploys to other ARM based hosts. I have previously build the images myself, but figured that I can't be the only one who would like hanko on more than one architecture.
- Added parameter in the Dockerfile's to enable building for multiple architectures
- Fixing the builder to the BUILDPLATFORM
- Utilizing GOs crossplatform builder to target TARGETARCH
- Let `buildx` handle the matrix (1x2, but not the less :)) from there
- Bumped Docker's Github Actions versions to get rid of warnings, hopefully
- Bumped the go version to 1.19 in the Dockerfile
Try running the action related to the workflow on this branch. There should be bulds for both amd64 and arm64 on ghcr.io afterwards.
There are other architectures available (linux/riscv64, …

Multiplatform docker

---

.github/workflows/release-frontend-sdk.yml
.github/workflows/release-hanko-elements.yml

Triggers a workflow on tags that have the form @teamhanko/elements@VERSION or @teamhanko/frontend-sdk@VERSION
When the version in the package.json differs from the VERSION in the tag the workflow fails. Otherwise the project is build and published to npm.

ci: add npm publishing/release workflows for elements and frontend-sdk

---

frontend/elements/package-lock.json
frontend/elements/package.json
frontend/elements/src/ui/pages/LoginEmail.tsx

Call the `login()` function again in case a conditional UI login failed, because an invalid WebAuthn credential has been used.
The autocompletion menu will appear again and you'll be able to select another credential.
Fixes #441

Fix conditional UI stops working on error

---

backend/config/config.go
backend/docs/Config.md
backend/go.mod
backend/go.sum
backend/handler/webauthn.go

Add a possibility to add an additional webauthn origin. With this change you can use hanko to let users login (with passkey) in the web through the web component and at the same time login in an native mobile app. 
Before this was not possible, because Android returns an APK key hash as an origin in the ClientData (e.g. "android:apk-key-hash:nLSu7wVTbnMOxLgC52f2faTnv...") and we only had the ability to check against one origin.
In order to accomplish it, the webauthn lib was replaced with our own fork (for now, until https://github.com/go-webauthn/webauthn/pull/81 is merged) and added a new config field where multiple origins can be provided.
Instead of providing the origin through the old `webauthn.relying_party.origin` field, use the new `webauthn.relying_party.origin` field.

Feat allow multiple webauthn origins

---

backend/config/config.go
backend/docs/Config.md
backend/persistence/persister.go

Adds a database url config variable for easier database configuration. As mentioned in #438 sometimes its easier just to use a url instead of different variables for all the config stuff.
Instead of the current database config use the new url variable with the scheme `dialect://username:password@localhost:port/database?sslmode=disable`.
Example:
```
database:
url: postgres://hanko:hanko@localhost:5432/hanko?sslmode=disable
```
Fixes #438

feat: add database url config variable

---

backend/handler/audit_log.go
backend/persistence/audit_log_persister.go
backend/test/audit_log_persister.go
docs/static/spec/admin.yaml

Add query parameters to the audit log endpoint in the admin API, so someone is able to search for specific audit logs.
I added some query parameter to the audit log endpoint which are used in the database queries. 
The `type` query parameter can be added multiple times so someone can search for multiple audit log types at the same time. One thing to note is, that to achieve this, the sql query (only for this part) was created using string concatenation, so the values might not be escaped and is a security vulnerability. This was necessary because of how the values are handed over to the database driver. But since this is an endpoint at in the admin API, this is fine (IMO).
To test this, just call the audit log endpoint with the queries you want.

feat: add query parameter for searching audit logs

---

frontend/elements/src/_preset.sass
frontend/elements/src/components/form/styles.sass

Button preset min-width set to a fixed value, so the button width remains the same, even when the loading spinner is displayed. Also the button width has been set to 100%, so it takes the available space.
Manually tested in Chrome, Firefox and Safari, also I checked the Quickstart app looks like before (except the button takes the available space)

fix: fix button width

---

docs/static/jsdoc/hanko-frontend-sdk/HttpClient.html
docs/static/jsdoc/hanko-frontend-sdk/Response.html
docs/static/jsdoc/hanko-frontend-sdk/lib_client_HttpClient.ts.html
docs/static/jsdoc/hanko-frontend-sdk/lib_client_PasscodeClient.ts.html
docs/static/jsdoc/hanko-frontend-sdk/lib_client_PasswordClient.ts.html
frontend/frontend-sdk/src/lib/client/HttpClient.ts
frontend/frontend-sdk/src/lib/client/PasscodeClient.ts
frontend/frontend-sdk/src/lib/client/PasswordClient.ts
frontend/frontend-sdk/tests/lib/client/HttpClient.spec.ts

Correct the method to parse the retry after header, so it always returns a number. 
I did the following:
- slightly adjusted the method to parse the value
- renamed the method from `parseXRetryAfterHeader` to `parseRetryAfterHeader`, so it's inline with the header name
- jsdoc removed from a non-existent parameter
Unit tests included.

Adjust method to parse the retry after header

---

backend/handler/user_admin.go
backend/persistence/user_persister.go
backend/test/user_persister.go
docs/static/spec/admin.yaml

Add `order` query parameter to the list user admin endpoint to control the order of the returned list.
The list is ordered by `created_at`, default = `desc`
Added the `order` query parameter and set default value to `desc`
Call the list user endpoint in the admin API and add the `order` query param and check the result.

feat: add order query for user list

---

backend/handler/user.go

Add the SameSite attribute explicitly to the workaround cookie for older frontend versions, so this works also in Chromimum browsers.

fix: add same site attribute to workaround cookie

---

e2e/pages/LoginPasscode.ts
e2e/tests/common.spec.ts
frontend/elements/src/pages/LoginPasscodePage.tsx

Changes the button text on the passcode page from "Sign In" to "Continue".
I just changed the translation key in the `LoginPasscodePage`component

fix(hanko-elements): change passcode button text

---

examples/svelte/package-lock.json
examples/svelte/package.json
examples/vue/package-lock.json
examples/vue/package.json

quick fix: when running with yarn vue and svelte are declared as 'self-referencing'.

examples:  use consistent naming schema

---

frontend/elements/package-lock.json
frontend/elements/package.json
frontend/elements/src/contexts/AppProvider.tsx
frontend/elements/src/pages/InitPage.tsx

In some Frameworks the `api` attribute is not set immediately, which causes `<hanko-auth>`and `<hanko-profile>` to throw an error.
* Show the loading spinner until the `api` attribute is defined.
* Do not access SDK properties (e.g. via useEffect dependencies) until the frontend-sdk object is available.

Show loading spinner until the api attribute is defined

---

quickstart/public/html/secured.html

The logout link was missing a "href" attribute, which causes the browser to display the wrong cursor.

fix(quickstart): use correct cursor for the logout link

---

quickstart/main.go
quickstart/public/html/index.html

Adds the ability to set experimental feature conditional ui in quickstart

feat: make conditional ui available via env var in quickstart

---

backend/cmd/isready/isready.go
backend/cmd/root.go

This PR introduces the `isready` subcommand for the Hanko CLI.
Fixes #697.
The command takes in the service to check (`public` or `admin`) and makes an HTTP request to the corresponding health endpoint. 
Tested manually.

`isready` subcommand to check if a service is ready to serve requests

---

docs/docs/guides/mobile_guide.mdx

Improve the mobile guide in the docs. The docs never mention the "Android APK Key Hash", which is necessary if passkeys should work in an android app.
Added an info block in the mobile docs section.

feat: add info about android apk key hash

---

backend/go.mod
backend/handler/user_admin_test.go
backend/persistence/migrations/20220425122015_create_password_credentials.down.fizz
backend/persistence/migrations/20221027123530_change_passcodes.down.fizz
backend/persistence/user_persister.go
backend/test/database.go
backend/test/fixtures/user_admin/emails.yaml
backend/test/fixtures/user_admin/users.yaml
backend/test/suite.go

Currently the list users admin endpoint returns all users regardless if they "really registered" (when email verification is `on` a user is first completely registered when he entered the passcode successful). These users can not do anything but they clutter the user table and the user list. So this PR excludes the users from the list users admin endpoint. 
Excluding the users from the list is done by just adding the `having` clause to the SQL query.
An other thing done in this PR is improving the test setup, so that the integration tests can easily run with a MYSQL database. I have done this, because I wanted to check if the SQL query would also work on MYSQL, which it does.
Also changed the user admin handler test to the new integration test style.
1. Start the backend with email …

Fix only return users with email

---

frontend/elements/src/Translations.ts
frontend/elements/src/components/accordion/AddEmailDropdown.tsx
frontend/elements/src/components/link/Link.tsx
frontend/elements/src/components/link/styles.sass

"Dangerous" links within `<hanko-profile>` now require an extra confirmation step. E.g. when deleting a passkey or email.
- Click a dangerous / red link (e.g. to delete an email or a passkey) and two links ("yes / no") will appear next to the link.
- When clicking "no" it returns to the original state.
- When leaving the link area with the mouse cursor for more than one second it should also return tho the original state.
- When the action has been confirmed by clicking "yes", the action will be executed.

Feat additional confirmation steps

---

frontend/elements/src/pages/DeleteAccountPage.tsx

* Fixes a bug on the `DeleteAccountPage` where the UI elements remain in the loading state after the deletion request returned an error.

fix: reset states after account deletion failes

---

backend/handler/email_test.go
backend/test/fixtures/email/emails.yaml
backend/test/fixtures/email/primary_emails.yaml
backend/test/fixtures/email/users.yaml

Update the email handler test to the new architecture.
Use the new test suite for the tests. 
Closes #620

test: update email handler tests

---

backend/README.md

Use correct docker image in the backend readme.

docs: use correct docker image in readme

---

frontend/elements/src/pages/LoginEmailPage.tsx

Removes the autofocus from the email input field due to the following request:
> Remove autofocus on email input in hanko-auth
> 
> - sub-optimal for conditional UI experience (click required to trigger CondUI, but user not inclined to click if input already focused)
> - Autofocus may interfere with other content outside of element

chore: remove autofocus from the email input field

---

backend/handler/well_known.go
backend/handler/well_known_test.go

Add the `Cache-Control` header when returning the `jwks.json` to use a consistent caching strategy.
Fixes #849 
Only adds the `Cache-Control` header when returning the `jwks.json`.
Currently it is not changeable through the config, I don't known if we want to have that, feel free to share your opinion.
- Start the public backend
- open `/.well-known/jwks.json`
- check that the `Cache-Control` header is set in the response.

feat: add cache control header when returning jwks.json

---

frontend/elements/README.md
frontend/elements/src/Elements.tsx
frontend/elements/src/contexts/AppProvider.tsx
frontend/elements/src/pages/LoginEmailPage.tsx

- Adds an option to the `register()` function to hide the "sign in with a  passkey" button on the login page. Whether the button is displayed or not, now depends on the `hidePasskeyButtonOnLogin` and the `enabledPasskeys` option. Enabling CUI will not hide the button, as it was the case before.
- Also refactors the "globalOptions" in the `Elements.tsx` file.

feat(hanko-elements): add 'hidePasskeyButtonOnLogin' options

---

frontend/elements/src/contexts/AppProvider.tsx

- Fixes the default translation is not used, when the "lang" attribute is not provided

fix(hanko-elements): translations shown when lang attribute is missing

---

frontend/elements/src/contexts/AppProvider.tsx
frontend/elements/src/pages/LoginEmailPage.tsx

Only pre-fill the email input with the `prefilled-email` when the `emailAddress` is empty, otherwise the input gets overridden by the value in `prefilled-email` after hitting the back button in the user creation page.
Fixes #923

fix: only set prefilledEmail when email input is empty

---

frontend/elements/package.json
frontend/package-lock.json

- Updates the `frontend-sdk` dependency version  to 0.8.1.
Fixes #936

fix: hanko-elements uses wrong frontend-sdk version

---

backend/dto/admin/email.go
backend/dto/admin/user.go
backend/dto/validator.go
backend/handler/admin_router.go
backend/handler/user_admin.go
backend/handler/user_admin_test.go
docs/static/spec/admin.yaml

As you can disable self registration (#947) a way to create new users is necessary. Currently you only can use the user import which is not the best way for machine-to-machine use cases. 
This PR adds a new route to the admin API where new users can be created.

Feat add create user admin endpoint

---

docs/docs/guides/backend.mdx

confirmed the backend guide is working, and updated the python backend guide. 
/closes #980 
/claim #980

docs: added the python backend guide

---

docs/docs/intro.md

Added the video tutorial on how to set up a project on the Hanko Cloud in the "Introduction" page of the Docs

Added the Hanko Cloud video tutorial to the Docs

---

docs/docs/guides/tutorials/php.mdx
docs/docusaurus.config.js
docs/src/components/EmbedGitHubFileContent.tsx

Replacing the non-functional emgithub script embeds with a custom react component to display content from GitHub files.
External embeds of GitHub files in the Symfony tutorial were replaced with a react component loading the code right from GH. Syntax highlighting for `twig` files does not work as of now (waiting for PrismJS/prism#3730 to be merged).

feat(docs): add github embeds

---

README.md

I provided a direct link to the hanko API, even though the link to the official documentation is already mentioned. I added the direct API reference link so that users can conveniently access the APIs in other languages directly from the provided link. This makes it easier for users and can save them some time as well.

added API link

---

backend/flow_api_test/flow.go
backend/flowpilot/builder.go
backend/flowpilot/context.go
backend/flowpilot/context_action_exec.go
backend/flowpilot/context_flow.go
backend/flowpilot/flow.go

- Sub-flows can now be started with any sub-flow state and they don't have initial states anymore in consequence
- Fixes an an issue with the `ContinueToPreviousState()` function
- Flow validation now happens when building the flow
- Refactoring

Flowpilot subflow updates and fixes

---

backend/flowpilot/builder.go
backend/flowpilot/context.go
backend/flowpilot/context_action_exec.go
backend/flowpilot/context_flow.go
backend/flowpilot/db.go
backend/flowpilot/flow.go

- you can now set a value to the flow, e.g. `bar := &Bar{}; Flow.Set("foo", bar)` and get the value within a flow action like `bar := c.Get("foo").(*Bar)`
- refactoring: the db wrapper interface and related structs and methods are now private.

feat: adds the possibility to set context values to the flow

---

backend/handler/passcode.go
backend/handler/passcode_test.go
backend/test/fixtures/passcode/emails.yaml

When creating a new email in the profile, the passcode can not be validated successfully on cross-domain scenarios, because the passcode handler only gets the sessionToken from a cookie and not from the `Authorization` header. So when you are logged in and want to create a new email, it fails. In this PR the passcode handler also gets the sessionToken from the `Authorization` header.
The passcode handler now also tries to get the sessionToken from the `Authorization` header.
Either host hanko in a cross domain scenario OR use the docker compose quickstart. 
When using the docker compose quickstart:
1. Login with an existing or create a new user
2. When in the profile create new email BUT do not verify it (stay at the screen where you can enter the passcode)
3. Get the `user_id` and …

fix: get session token from header for passcode finalization

---

backend/flow_api_basic_construct/actions/get_wa_creation_options_test.go
backend/flow_api_basic_construct/actions/send_wa_attestation_response.go
backend/flow_api_basic_construct/actions/send_wa_attestation_response_test.go
backend/flow_api_basic_construct/common/actions.go
backend/flow_api_basic_construct/flows/passkey_onboarding.go
backend/flow_api_basic_construct/flows/registration.go
backend/test/fixtures/actions/get_wa_creation_options/flows.yaml
backend/test/fixtures/actions/send_wa_attestation_response/flows.yaml
backend/test/fixtures/actions/send_wa_attestation_response/webauthn_session_data.yaml

Add tests for webauthn actions.

Webauthn creation tests

---

frontend/elements/src/contexts/AppProvider.tsx

The passkey list in the profile remained empty after account creation (incl. passkey onboarding), when embedding hanko-auth and hanko-profile on the same page. 
- Changed the profile to initialize when the "onAuthFlowCompleted" has been received (instead of "onSessionCreated").
fixes #1138

fix: reload the profile after passkey creation

---

backend/flow_api/flow/login/flow.go
backend/flow_api/flow/profile/flow.go
backend/flow_api/flow/registration/flow.go
backend/flow_api/handler.go
backend/flowpilot/builder.go

With current implementation of the flow builder and how it is used, each request shared the same flow instance, this leads to a concurrency issue, because the flow instance holds the database transaction and http context of a request. And when all incoming request share the same flow instance, the transaction and http context get overridden and also we get a `concurrency write` error on the contextValue variable in the flow.
Create a new instance of a flow for each incoming request. The `scanFlowStates` function from the `defaultFlowBuilder` is changed, that this only runs once.
Call an endpoint e.g. `/registration` automated (concurrent) many times (at least one action should be used e.g. `register_client_capabilities`). Check that no errors occur.

fix: fix concurrency issue

---

backend/README.md
backend/docs/Config.md

This PR extends the backend documentation with a chapter for webhooks and all configuration parameters

chore(docs): add webhook docs

---

backend/webhooks/webhook.go
backend/webhooks/webhook_test.go

* fix premature return in the check which skips all following events when the first one was false
* add test cases
Closes: #1354

fix(webhooks): fix HasEvent logic

---

backend/README.md

Fixing broken links to the API documentation in backend/README.md.
Trivial documentation update to fix a couple of broken links to docs.hanko.io.

Fix links in README.md

---

backend/dto/email.go
backend/handler/user.go

* add check of email object is nil to DTO transformation - prevents runtime nil exception
* fetch updated emails for user before creating session token

fix(jwt): add updated email on user create

---

backend/ee/saml/handler.go
backend/handler/thirdparty.go
backend/thirdparty/linking.go

With the introduction of the `allow_linking` parameter for the thirdparty social provider the saml login is broken when an account for the email already exists.
Only check the `allow_linking` parameter while linking to an already existing user when it is not a saml provider.
Configure a saml provider and try to login with an already existing user.

fix: fix saml login for existing users

---

backend/flow_api/flow/login/action_continue_with_login_identifier.go
backend/flow_api/flow/shared/errors.go

- Enables the UI to differentiate between the login identifier options, both email and username, or exclusively emails or usernames.
- Additionally, introduces a new error type for handling unknown usernames, enabling the UI to respond accordingly.
Previously, there was one input field named 'identifier', but in the UI, the placeholder in the input field should indicate whether the user can enter an email, a username, or both. Therefore, individual fields are now available. The introduced private method `analyzeIdentifierInputs()` checks the user input and determines, from the individual fields, the information of the input field expected based on the backend configuration.

chore: individual input fields for 'identifier', 'email' and 'username'

---

backend/flow_api/flow/login/flow.go
backend/flow_api/flow/registration/flow.go
backend/flow_api/flow/shared/hook_get_user_data.go
frontend/frontend-sdk/src/lib/flow-api/types/payload.ts
frontend/frontend-sdk/src/lib/flow-api/types/state-handling.ts

After a successful registration or login, the payload of the success state now includes the user object. This is needed to modify the JavaScript event "hanko-session-created" to include this data.
- A new hook has been implemented to gather data from the database and add the user model to the payload.
- The type interfaces of the JS SDK have been modified accordingly

feat: add user data to payload on success

---

backend/handler/webauthn.go

When registering a webauthn credential fails the internal error is overridden and therefore not returned.
The error is overridden by an auditLogger error, now the auditLog error is now assigned to a new variable instead.
Create a webauthn config where `origins` is not set correct (e.g. "https://example.com") and try to register a new webauthn credential. Before the fix the error on the logs on show `code=400, message=failed to validate attestation`. With the fix it should include the internal error `code=400, message=failed to validate attestation, internal=Error validating origin`

fix: don't override error before return

---

backend/mail/locales/passcode.en.yaml

Passcodes are not only used for logins, but also for email verification. This PR aims to generalize the wording to reflect that.

fix: improve passcode email text

---

backend/flow_api/handler.go
backend/flowpilot/errors.go
backend/flowpilot/response.go

Uses zerolog to log requests to the flow API. The logging middleware from echo could be used but an error from the flow API would not be logged. Thats because the handler function would need to return an error in order to be logged by the middleware, but the flow API handler does not return an error. So the handler logs the requests itself with zerolog.
The logs from the flow API handler and from the middleware should log the same values. Currently the middleware logs more values that the flow API handler. We should check which values are needed and which we can remove.

add flow api logging

---

backend/flow_api/handler.go
backend/flowpilot/context.go
backend/flowpilot/flow.go
backend/flowpilot/stash.go

Adds a new execution option `UseCompression(bool)` to the Flowpilot. It controls whether the stash data should be compressed or not. The Flow API will enable compression when `config.Debug` is `false` or store the stash contents as plaintext otherwise.

Compress stash data

---

backend/flow_api/flow/profile/action_username_create.go
backend/flow_api/flow/profile/action_username_update.go

Respect the length requirements of the username when creating or changing it. Currently when the username is set or changed in the profile the username can have any length and the config parameters have no effect. Also this is true when the username is set during a login flow.

fix: respect length requirements username

---

backend/dto/user.go
backend/flow_api/flow/credential_onboarding/action_webauthn_generate_creation_options.go
backend/flow_api/flow/credential_onboarding/action_webauthn_verify_attestation_response.go
backend/flow_api/flow/credential_usage/action_continue_with_login_identifier.go
backend/flow_api/flow/credential_usage/action_webauthn_verify_assertion_response.go
backend/flow_api/flow/profile/action_email_delete.go
backend/flow_api/flow/profile/action_username_delete.go
backend/flow_api/flow/profile/action_username_update.go
backend/flow_api/flow/profile/action_webauthn_credential_create.go
backend/flow_api/flow/profile/action_webauthn_verify_attestation_response.go
backend/flow_api/flow/shared/action_exchange_token.go
backend/flow_api/services/webauthn.go
backend/handler/user.go
backend/persistence/models/user.go
backend/test/user_persister.go
docs/static/jsdoc/hanko-frontend-sdk/Email.html
docs/static/jsdoc/hanko-frontend-sdk/Emails.html
docs/static/jsdoc/hanko-frontend-sdk/Identity.html
docs/static/jsdoc/hanko-frontend-sdk/Passcode.html
docs/static/jsdoc/hanko-frontend-sdk/User.html
docs/static/jsdoc/hanko-frontend-sdk/UserCreated.html
docs/static/jsdoc/hanko-frontend-sdk/WebauthnCredential.html
docs/static/jsdoc/hanko-frontend-sdk/WebauthnCredentials.html
docs/static/jsdoc/hanko-frontend-sdk/WebauthnTransports.html
docs/static/jsdoc/hanko-frontend-sdk/lib_Dto.ts.html
frontend/frontend-sdk/src/lib/Dto.ts

- Added `username` field to the DTO
- Refactored email and username fields to use string pointers across the application for better nil handling
- The response of `hanko.user.getCurrent()` now contains the username

feat: update DTO with username field

---

backend/cmd/user/import_test.go
backend/dto/admin/identity.go
backend/dto/admin/password.go
backend/dto/admin/user.go
backend/dto/admin/username.go
backend/handler/user_admin.go
backend/handler/user_admin_test.go
backend/handler/user_test.go
backend/persistence/user_persister.go
backend/test/user_persister.go

Add username, identities and password credential to the return object when calling /users/{user_id} from the admin API.
The password credential does not include the password hash, only the metadata is returned.
The added information is always returned without considering the config, e.g. when password credentials are associated with users they are also returned when passwords are disabled by the config.

feat: return complete user in admin API

---

backend/ee/saml/provider/saml.go

Fix the email_verified check in the Hanko SAML provider.
Currently it is only check if the field in the SAML response is not an empty string, but when the SAML provider returns `false` for the email_verified field the Hanko SAML provider interprets it as `true`. Now it check if the value is `true` and when it is not, the email_verified field in Hanko will be set to `false`.
E.g. Use the quickstart app and setup SAML in hanko and login with an user which email is not verified and check in the profile that the email is not verified.

fix: fix email verified check for saml

---

backend/flow_api/flow/flows.go
backend/flow_api/handler.go

Create a new flow for every request, because the flowBuilder is not save for concurrent usage.

fix: create new flow for every request

---

backend/flow_api/flow/credential_usage/action_webauthn_verify_assertion_response.go

When using an unknown / invalid passkey, the error page with the corresponding error message will be displayed.

fix: passcode invalid error not shown

---

backend/flow_api/flow/credential_usage/action_password_login.go
backend/flow_api/flow/credential_usage/action_resend_passcode.go
backend/flow_api/flow/credential_usage/hook_send_passcode.go
backend/flow_api/flow/profile/action_account_delete.go
backend/flow_api/flow/registration/action_register_login_identifier.go
backend/flow_api/services/passcode.go
backend/handler/admin_router.go
backend/handler/passcode.go
backend/handler/public_router.go
backend/handler/thirdparty.go
backend/handler/user.go
backend/handler/user_admin.go
backend/middleware/webhook.go
backend/webhooks/manager.go
backend/webhooks/manager_test.go
backend/webhooks/utils/webhook.go
backend/webhooks/utils/webhook_test.go

Only use the initiated transaction connection when connecting to the database. When the transaction connection is not used inside of a transaction block, the connection pool can run out of connections and block the whole application, because a transaction blocks the one connection until the transaction is finished.
E.g. when 5 requests are incoming (on the same time) on the flow API endpoints and trigger the `register_login_identifier` a passcode is created, stored into the db, the current implementation created the passcodeModel with a different connection, because all connections are used (because of the incoming requests) and the pool cannot create new connections, all requests are blocked.
Always use the transaction connection in a transaction block.
I used …

fix: only use transaction connection in a transaction

---

backend/config/config.go
backend/config/config.yaml
backend/config/config_default.go
backend/config/config_mfa.go

Adds new configuration parameters as specified:
- `mfa`
- `enabled`
- type: bool
- default: true
- `optional`
- type: bool
- default: true
- `acquire_on_registration`
- type: bool
- default: true
- `acquire_on_login`
- type: bool
- default: false
- `totp`
- `enabled`
- type: bool
- default: true
- `security_keys`
- `enabled`
- type: bool
- default: true
- `user_verification`
- type: string
- enum: "required, preferred, discouraged"
- default: “discouraged”
- `attestation_preference`
- type: string
- enum: "direct, indirect, none"
- default: “direct”
- `authenticator_attachment`
- type: string
- enum: ”platform, cross-platform, no_preference"
- default: “cross-platform”
- `limit`
- type: int
- default: 10

feat: add mfa config

---

backend/mail/locales/passcode.zh-CN.yaml

The existing template for Chinese passcode emails was incomplete and caused the API to crash when a corresponding language header was set in the request. This PR includes a completed and revised template provided by a community member.

fix: chinese email template corrected

---

oss.gg/10_feedback_fanatic.md
oss.gg/11_quest_wizard.md
oss.gg/1_bug_hunter.md
oss.gg/20_test_drive_hanko.md
oss.gg/21_technical_article.md
oss.gg/22_build_your_own_app.md
oss.gg/2_accessibility_advocate.md
oss.gg/3_meme_magic.md
oss.gg/4_gif_magic.md
oss.gg/5_follow_on_linkedin.md
oss.gg/6_follow_on_x.md
oss.gg/7_starry_eyed_supporter.md
oss.gg/8_enhanced_docs.md
oss.gg/9_unlock_more_side_quests.md

Add side quests for oss.gg

---

backend/dto/profile.go
backend/flow_api/flow/credential_usage/action_continue_to_passcode_confirmation_recovery.go
backend/flow_api/flow/profile/hook_get_profile_data.go
backend/flow_api/flow/shared/action_exchange_token.go
backend/flow_api/flow/shared/const_stash_paths.go
backend/flow_api/flow/shared/hook_get_user_data.go
backend/flow_api/flow/shared/hook_issue_session.go
frontend/elements/src/Elements.tsx
frontend/elements/src/contexts/AppProvider.tsx
frontend/frontend-sdk/src/lib/flow-api/types/payload.ts

The 'success' state can now contain data about the recent login. This data is stored in localStorage and can be accessed during the next login via the 'AppProvider' to, for example, label certain buttons in the UI with 'last used'.

Feat: remember last used login method

---

backend/config/config_mfa.go

When using this project as an dependency in an other app, the `omitempty` can have a negative impact when these are used for frontend development.

chore: remove omitempty from boolean

---

frontend/elements/src/components/accordion/AddWebauthnCredentialDropdown.tsx
frontend/elements/src/components/accordion/ManageAuthAppDropdown.tsx
frontend/elements/src/i18n/bn.ts
frontend/elements/src/i18n/de.ts
frontend/elements/src/i18n/en.ts
frontend/elements/src/i18n/fr.ts
frontend/elements/src/i18n/it.ts
frontend/elements/src/i18n/pt-BR.ts
frontend/elements/src/i18n/translations.ts
frontend/elements/src/i18n/zh.ts

- Missing translations have been added.
- Removed all references to platform authenticator details.
- Updated the "Set up security key" text to match the display on the "stand-alone" page.
- Changed the link text for deleting the OTP secret to simply "Delete".

feat: add missing translations

---

.github/ISSUE_TEMPLATE/oss-gg-hack-submission.yml

Added oss-gg hackathon issue opening template

---

backend/flow_api/flow/profile/action_webauthn_verify_attestation_response.go

The `webauthn_verify_attestation_response` action was disabled when passkeys are disabled or whne no webauthn is available on the device. But when security keys and MFA are also enabled, the action is need t in order to create a security key.
Only suspend the `webauthn_verify_attestation_response` action when passkeys, and security keys are disabled.
Try to create a new security key when passkeys are disabled.

fix: do not suspend webauthn action for MFA

---

backend/audit_log/logger.go
backend/dto/admin/session.go
backend/dto/validator.go
backend/handler/admin_router.go
backend/handler/session_admin.go
backend/persistence/migrations/20241106171500_change_sessions.down.fizz
backend/persistence/migrations/20241106171500_change_sessions.up.fizz

Add a session creation endpoint in the admin API.

feat: add session creation endpoint

---

backend/handler/public_router.go
backend/middleware/session.go

Check server side sessions in session middleware for REST API endpoints. Without it a server side session could be deleted, but can still be used at the REST API endpoints.
When server side sessions are enabled, check if the session is still stored in the database.
Delete a server side session and check that the REST API endpoints return `Unauthorized` when the deleted session token is used.

fix: check server side session for REST API endpoints

---

backend/handler/passcode.go

Use configured cookie name in passcode handler. Fixes #1624

Fix cookie name in passcode handler

---

backend/config/config_third_party.go

Add missing tags for deserialisation. Just to be consistent with all config parameters.

chore: add missing tags

---

quickstart/middleware/session.go

Let the quickstart app use the session validate endpoint instead of validating the JWT itself with the JWKS.
Call the `sessions/validate` endpoint in the session middleware.

feat: let quickstart use session validate endpoint

---

backend/handler/thirdparty_auth_test.go
backend/test/database.go
backend/thirdparty/provider.go

When trying to get a third party provider the lowered id must be used. This was already in place for getting custom third party providers, but was missing for the predefined ones.

fix: use lowered id to get third party provider

---

backend/config/config.go

The config loading mechanism always tries to unmarshal the config file, even when it could not be loaded. The file should only be unmarshalled when the file could be loaded successfully.
Move the `Unmarshal` function into the if statement where we know that the file was loaded successfully.
Try to start the backend with missing config file.

fix: don't use config file when failed to load

---

backend/dto/session.go
backend/handler/session.go

This PR introduces improvements to the session validation process, focusing on extracting claims from JWT tokens.
- dto/session.go:
- Added a new Claims struct to represent JWT claims, providing a standardized structure for parsing token data.
- Implemented `GetClaimsFromToken` function for parsing and validating JWT token claims.
- Updated `ValidateSessionResponse` to include the Claims field while keeping deprecated fields (ExpirationTime, UserID) for backward compatibility.
- handler/session.go:
- Replaced manual token parsing with `GetClaimsFromToken` for extracting claims.
- Simplified logic in `ValidateSession` and `ValidateSessionFromBody` handlers:
- Validated session IDs and claims directly.
- Updated response payload to use the new Claims structure.
- Deprecate usage of …

feat: enhance session response

---

backend/flow_api/flow/credential_usage/action_webauthn_verify_assertion_response.go
backend/flow_api/flow/login/hook_webauthn_generate_request_options_cond.go
backend/flowpilot/context_action_exec.go
frontend/elements/src/contexts/AppProvider.tsx

This PR fixes the following issues:
- When using a passkey that has been deleted on the server, the error message “This passkey cannot be used anymore” does not get shown (only when using the passkey button).
- When the first try to login with a passkey fails, the user can not login with a passkey anymore. The user needs to reload the page to be able to login with a passkey (when using conditional ui).
- The first issue was resolved by saving the current state error into the `uiState` after the "back" action is triggered. This ensures that the new state does not overwrite the pre-existing WebAuthN errors. Additionally, the flow API has been updated to avoid transitioning into an error state, as the UI should not display the error page in such cases.
- To address the second issue where a …

fix: error handling when using zombie passkeys

---

frontend/elements/src/contexts/AppProvider.tsx
frontend/elements/src/pages/LoginInitPage.tsx
frontend/elements/src/pages/RegistrationInitPage.tsx

Fixes an issue where clicking a third-party button, with multiple providers configured, incorrectly displays the loading spinner on all third-party buttons.
Configure multiple third-party providers and click the buttons on the login or registration page. Verify that the loading spinner appears only on the buttons you clicked.

fix: third party loading spinner shown on multiple buttons fixed

---

backend/cmd/cleanup/cleanup.go
backend/cmd/root.go
backend/config/config.yaml
backend/config/config_audit_log.go
backend/config/config_default.go
backend/flow_api/handler.go
backend/json_schema/hanko.config.json
backend/persistence/audit_log_persister.go
backend/persistence/flow_persister.go
backend/persistence/models/audit_log.go
backend/persistence/persister.go
backend/persistence/webauthn_session_data_persister.go

This PR adds a new `cleanup` command to the backend, enabling automated database cleanup for expired entities. 
- **New `cleanup` command**:  
- Implemented using `cobra` CLI framework.  
- Supports dry-run mode and execution mode (`--run`).  
- Allows specifying individual tables to clean up (`--tables` flag).  
- **Added cleanup logic for**:  
- `audit_logs`: Uses a retention period from the configuration.  
- `flows` and `webauthn_session_data`: Deletes expired entries based on timestamps.  
- **Configuration updates**:  
- Introduced `audit_log.retention` in `config.yaml` (default: 720 hours).  
- Added validation for retention duration in `config_audit_log.go`.  
- **Persistence layer updates**:  
- Extracted `FlowPersister` from `flowdb.go` and moved it to `flow_persister.go`.  
- …

feat: add cleanup command to remove expired db entries

---

backend/config/config.go
backend/config/config_default.go
backend/config/config_session.go

Reintroduce server-side session config for backward compatibility.
When server-side sessions are enabled set the "new" session config parameters. This behaviour can be disabled by setting 
`convert_legacy_server_side_session_config` to `false`.

fix: reintroduce server-side session config

---

backend/handler/passcode.go
backend/handler/password.go
backend/handler/token.go
backend/handler/utils.go
backend/handler/webauthn.go
backend/test/config.go

The old endpoints do not store the session in the DB, this leads to an unauthorized error in old hanko elements versions prior 1.0.0 when any endpoint is called that requires a session because they check if the session is stored in the DB.
Also store the session in the DB in the old endpoints that are used by hanko-elements prior 1.0.0.

fix: create session in DB for old endpoints

---

backend/handler/thirdparty_callback_test.go
backend/handler/thirdparty_test.go
backend/thirdparty/provider_apple.go

The email_verified claim in the apple identity token can either be a string or a bool (see [here](https://developer.apple.com/documentation/sign_in_with_apple/authenticating-users-with-sign-in-with-apple) for more info about the claims). Before it was assumed that it is always a string, but when the claim is of type bool an error is returned. Now the claim type is checked and parsed accordingly. Also when the type check or parsing fails it is assumed that the email is not verified.
Check the type of the `email_verified` claim before parsing it accordingly to the type. Also removed an error when the claim could not be parsed. Now a warning is logged when the claim could not be parsed or if the type is not `string` or `bool`.
Added a test case where the `email_verified` claim is of type …

Parse email_verified claim correctly from Apple ID token

---

backend/flow_api/flow/profile/action_account_delete.go

When a user is deleted through the Flow API the application throws a nil pointer dereference error.
The `NotifyUserChange` function tries to get the user from the database but since the user was deleted the user is not present anymore and therefore `nil` is returned. To fix it, the account delete event is triggered through `TriggerWebhook`.

fix: use TriggerWebhook function instead of NotifyUserChange

---

backend/config/config.go
backend/config/config_default.go
backend/config/config_privacy.go
backend/flow_api/flow/credential_usage/action_continue_with_login_identifier.go
backend/flow_api/flow/registration/action_register_login_identifier.go
backend/flow_api/flow/shared/errors.go
frontend/elements/src/i18n/bn.ts
frontend/elements/src/i18n/de.ts
frontend/elements/src/i18n/en.ts
frontend/elements/src/i18n/fr.ts
frontend/elements/src/i18n/it.ts
frontend/elements/src/i18n/pt-BR.ts
frontend/elements/src/i18n/translations.ts
frontend/elements/src/i18n/zh.ts

Add two privacy settings, one that disables account enumeration protection (`show_account_existence_hints`) and one that only returns actual configured login methods of the user (`only_show_actual_login_methods`).
Although otherwise discussed these two settings also have an effect when email verification is disabled. And therefore the settings are added to a `privacy` section in the settings.
Added some checks that if the settings are enabled an error might be returned e.g. the account or email does not exist.
Enable and disable email, email.use_for_authentication , username, password and check that errors are returned when user already exists or does not exists and that only authentication methods are returned that the user has configures. 
MFA methods are not changed because they are …

feat: add privacy settings

---

backend/flow_api/flow/credential_usage/action_continue_with_login_identifier.go
backend/flow_api/flow/credential_usage/action_webauthn_generate_request_options.go
backend/flow_api/flow/flows.go
backend/flow_api/services/webauthn.go
frontend/elements/src/pages/LoginMethodChooser.tsx
frontend/frontend-sdk/src/lib/flow-api/types/action.ts

Add a passkey option to the login method chooser when the `privacy.only_show_actual_login_methods` option is set to `true`. Also, when passkey is the only option to login for a user and the user enters his identifier, the webauthn api is triggered automatically.
When the user enters his identifier, it is checked which login method he can use and decided if the login method chooser is show, or when the user only has one login method if it should be triggered automatically.
Set `privacy.only_show_actual_login_methods` to `true` in the config and create users with different login methods available and try to login with them.

feat: add passkey option to login method chooser

---

backend/flow_api/flow/credential_usage/action_continue_to_passcode_confirmation.go
backend/flow_api/flow/credential_usage/action_continue_to_password_login.go

Fix the login method chooser when `privacy.only_show_actual_login_methods` is set to `true`. When the user had no password the password option was still present, but must not. Also when `email.use_for_authentication` is set to `false`, the passcode option was still present, but must not.

Fix login method chooser

---

frontend/elements/src/example.html
frontend/frontend-sdk/README.md
frontend/frontend-sdk/src/Hanko.ts
frontend/frontend-sdk/src/lib/Dto.ts
frontend/frontend-sdk/src/lib/client/UserClient.ts
frontend/frontend-sdk/src/lib/flow-api/State.ts
frontend/frontend-sdk/tests/lib/client/UserClient.spec.ts

This pull request enhances the Hanko Frontend SDK by introducing new session management functions (getUser, validateSession, getSessionToken, and logout) and updating related documentation and example code. 
- `Hanko.ts`: Added `getUser()`, `validateSession()`, `getSessionToken()`, `logout()` including JSDoc. 
-  Made `hanko.client`, `hanko.relay` public readonly; `hanko.session`, `hanko.user`, `hanko.cookie` private readonly.
- `README.md`: Added "Session Management" section with examples for new functions.
- `example.html`: Updated to use `hanko.validateSession()` and `hanko.logout()` instead of deprecated methods.
- `State.ts`:Simplified Options type using Omit.

chore: add new convenience functions to the sdk

---

frontend/elements/README.md
frontend/elements/src/Elements.tsx
frontend/elements/src/contexts/AppProvider.tsx

Removes the observable attribute `experimentalFeatures`  from `hanko-elements`, that is unused, since "autofill assisted requests" are always enabled.

chore: remove unused attribute for experimental features

---

backend/flow_api/flow/credential_usage/action_password_recovery.go

Adds missing validation to the recovery action, so that the API returns an appropriate error.

fix: add missing validation to the pw recovery action

---

frontend/frontend-sdk/src/lib/events/Relay.ts

Cross tab communication was not working due to wrong broadcast channel name.

fix: use correct broadcast channel name

---

frontend/elements/README.md
frontend/elements/src/Elements.tsx
frontend/elements/src/contexts/AppProvider.tsx

This PR adds a mode attribute to `<hanko-auth>`, allowing to specify whether the component initializes the "login" or "registration" flow.

feat: add 'mode' attribute to hanko-auth

---

frontend/elements/src/Elements.tsx
frontend/elements/src/declarations.d.ts

The JSX namespace was moved to the react module. More information can be found [here](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#the-jsx-namespace-in-typescript).
For backward compatibility the old namespace is still present.
Update the react dependencies to version 19 in the react example and try to build it.
Fixes #2053

fix: add types for react 19

---

backend/config/config_webauthn.go
backend/flow_api/flow/shared/action_thirdparty_oauth.go
backend/go.mod
backend/go.sum
backend/handler/user_test.go
backend/persistence/models/email.go
backend/persistence/models/user.go
backend/thirdparty/linking.go

Implement a case insensitive account linking functionality for third-party authentication.
Fixes #2193
Lowercase payload of userData.Metadata.Email
Refactored `golang.org/x/exp/slices` to use `slices` instead.
Register with any email. Try your Microsoft account for login, which might have an uppercase email configured and it should link the account correctly.
Maybe prepare a migration for persisted emails which are not yet lowercased.

fix: oauth third party authentication with case insensitive email
