- README.md
- deploy/docker-compose/quickstart.yaml
- deploy/k8s/base/deployment.yaml
- deploy/k8s/base/kustomization.yaml
- deploy/k8s/base/services.yaml
- deploy/k8s/overlays/quickstart/hanko-config.yaml
- deploy/k8s/overlays/quickstart/ingress.yaml
- deploy/k8s/overlays/quickstart/kustomization.yaml
- deploy/k8s/overlays/quickstart/namespace.yaml
- deploy/k8s/postgres/deployment.yaml
- deploy/k8s/postgres/initdbscript.sh
- deploy/k8s/postgres/kustomization.yaml
- deploy/k8s/postgres/persistent-volume.yaml
- deploy/k8s/postgres/service.yaml
and quickstart overlay including postgres pod
> feat: basic kubernetes manifests

- backend/server/admin_router.go
- backend/server/middleware/logger.go
- backend/server/public_router.go
- example/main.go
The log format did not produce valid json. This PR fixes that and removes redundancy.
> Fix log format

- hanko-js/src/ui/components/Button.tsx
- hanko-js/src/ui/components/ErrorMessage.module.css
- hanko-js/src/ui/components/Form.tsx
- hanko-js/src/ui/components/InputPasscodeDigit.tsx
- hanko-js/src/ui/components/InputText.tsx
- hanko-js/src/ui/pages/LoginEmail.tsx
- hanko-js/src/ui/pages/LoginFinished.tsx
- hanko-js/src/ui/pages/RegisterAuthenticator.tsx
- hanko-js/src/ui/pages/RegisterConfirm.tsx
If there is only one button on a page, select it so that you can use the UI without any mouse clicks.
> Hanko js auto focus buttons

- backend/config/config.go
* Explicitly adds json yaml and koanf tags to all config parameters
* Simplifies the config file selection
> Feat config json tags

- .github/workflows/docker-publish.yml
- deploy/docker-compose/quickstart.yaml
- example/main.go
- example/public/html/index.html
Release hanko example as Dockerfile template the index.html to allow different values for hanko api and hanko-js.
> Feat example generalized

- backend/dto/intern/WebauthnCredential.go
- backend/handler/user.go
- backend/handler/webauthn.go
- backend/persistence/migrations/20220711121022_create_credential_transports.down.fizz
- backend/persistence/migrations/20220711121022_create_credential_transports.up.fizz
- backend/persistence/models/webauthn_credential.go
- backend/persistence/models/webauthn_credential_transport.go
- backend/persistence/user_persister.go
- backend/persistence/webauthn_credential_persister.go
- hanko-js/package-lock.json
- hanko-js/package.json
- hanko-js/src/lib/HankoClient.ts
- hanko-js/src/lib/WebauthnSupport.ts
- hanko-js/src/ui/contexts/PageProvider.tsx
- hanko-js/src/ui/pages/LoginEmail.tsx
* Improves login flow: enter a known email, click "Continue" and the WebAuthN dialog will be displayed if a credential was previously registered.
* Credential transports will be stored
* Allowed credentials will be transmitted during authentication
TODO: Update e2e tests
> Feat handle allowed credentials and transports

- hanko-js/src/ui/components/InputPasscodeDigit.tsx
- hanko-js/src/ui/pages/LoginEmail.tsx
- hanko-js/src/ui/pages/LoginPassword.tsx
- hanko-js/src/ui/pages/RegisterPassword.tsx
Adds correct input types and autocomplete properties
> fix input type, id, autocomplete

- .github/workflows/docker-publish.yml
Build & publish the hanko-js docker container.
> build & publish hanko-js docker container

- e2e/package-lock.json
- e2e/package.json
see also: https://github.com/microsoft/playwright/issues/15717
> fix(e2e): playwright loader error

- e2e/pages/LoginEmail.ts
- e2e/pages/RegisterAuthenticator.ts
- hanko-js/src/ui/Translations.ts
Most importantly "Sign in with *a* passkey" to follow recommendations made by FIDO Alliance
> Small wording changes

- e2e/pages/RegisterAuthenticator.ts
- elements/src/ui/Translations.ts
- elements/src/ui/pages/RegisterAuthenticator.tsx
Small changes to the texts on the passkey creation UI.
> Passkey creation view minor text improvements

- elements/src/ui/pages/LoginEmail.tsx
Just a little cleanup.
Re-doing this PR because of git signing issues.
> Remove console log

- backend/handler/passcode.go
- backend/handler/passcode_test.go
- frontend-sdk/src/lib/client/PasscodeClient.ts
> fix: send 401 when passcode is not found instead of 404

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Browser Version should be asked in a Bug Report.
> Ask for Browser in BugReport

- .github/ISSUE_TEMPLATE/config.yml
Add link to the slack community to the issue templates
> Add link to the slack community to the issue templates

- docs/static/spec/public.yaml
- Add missing error responses
- Remove error responses
- Adjust/fix descriptions/property types
- Add examples
> docs: misc api spec fixes, adjustments

- .github/ISSUE_TEMPLATE/config.yml
> Use Discussions rather than the slack community

- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
Make solution (ideal solution & workarounds/alternatives) sections optional in feature request template.
> ci: make solution sections optional in feature request template

- README.md
New community section to encourage using discussions and issues instead of asking questions on Slack right away.
> rewrite community section

- frontend/frontend-sdk/package-lock.json
- frontend/frontend-sdk/package.json
Add `jsdoc` as dev dependency and fix doc build output destination
> fix: frontend sdk doc build

- docs/docs/guides/react.mdx
Fix code examples in react guide.
Closes #396
> docs: fix code examples in react guide

- docs/docs/guides/mobile_guide.mdx
- docs/sidebars.js
Add a simple guide for how to use the backend with mobile devices, because currently we have no SDK for mobile devices.
> docs: add a simple guide for mobile

- backend/docs/Config.md
Add missing  'emails' section to Config.md
> fix(backend): add 'emails' section to Config.md

- .github/workflows/release-frontend-sdk.yml
- frontend/frontend-sdk/package.json
> fix: frontend-sdk build and and publish now in one step

- .github/workflows/release-frontend-sdk.yml
> fix: add registry-url

- frontend/elements/README.md
- Correct link to the example apps readme file
- Add a link to example.hanko.io
- Rearrange the "Browser support" section
> Update hanko-elements README

- frontend/elements/package.json
> release:bump elements version

- frontend/frontend-sdk/package-lock.json
- frontend/frontend-sdk/package.json
> chore: update frontend-sdk 0.2.0

- frontend/elements/package-lock.json
- frontend/elements/package.json
- frontend/frontend-sdk/package.json
> Feat release elements

- frontend/frontend-sdk/src/lib/client/UserClient.ts
- frontend/frontend-sdk/src/lib/client/WebauthnClient.ts
> chore: optimize imports

- .github/dependabot.yml
fix: according to: https://github.com/dependabot/dependabot-core/issues/4993#issuecomment-1289133027 this should fix the dependabot
> Fix: Ci Dependabot producing failing builds

- backend/test/suite.go
now uses uuids for docker container names.
> fix: use uuid for docker database container names in test

- frontend/elements/README.md
- frontend/elements/src/_preset.sass
- frontend/elements/src/_variables.sass
- frontend/elements/src/components/spacer/Divider.tsx
- frontend/elements/src/components/spacer/styles.sass
Removes the `--divider-display` css variable.
> remove divider-display variable

- backend/cmd/jwt/create.go
- backend/config/config.go
- backend/docs/Config.md
- backend/go.mod
- backend/go.sum
- backend/handler/public_router.go
- backend/handler/thirdparty_test.go
- backend/handler/user_test.go
- backend/session/session.go
- backend/session/session_test.go
Adds the ability to define config: Sessions.Issuer which gets used in the JWT iss claim, if set.
The field is optional.
* add config option to docs
*
> Feat add iss and aud claims

- backend/handler/email_test.go
> fix: tests now passing again.

- frontend/elements/README.md
> chore: fix typo

- .github/workflows/go.yml
- backend/Dockerfile
- backend/Dockerfile.debug
- backend/go.mod
- quickstart/Dockerfile
> feat: update go version to 1.20

- frontend/examples/README.md
- frontend/examples/angular/README.md
- frontend/examples/express/README.md
- frontend/examples/nextjs/README.md
- frontend/examples/react/README.md
- frontend/examples/svelte/README.md
- frontend/examples/vue/README.md
Fix some broken links in the examples folder.
> docs: fix broken links

- backend/handler/password_test.go
- backend/test/fixtures/password/emails.yaml
- backend/test/fixtures/password/password_credentials.yaml
- backend/test/fixtures/password/primary_emails.yaml
- backend/test/fixtures/password/users.yaml
Improve password handler tests.
closes #622
> test: improve password handler test

- docs/static/spec/public.yaml
Fixes a mismatch between the API spec and how the API actually work.
Closes #783
> docs: fix mismatch with actual code

- backend/handler/well_known_test.go
Well known handler test now uses the test suite.
Closes #626
> test: use test suite for well known tests

- frontend/elements/README.md
> fix: remove duplicate section

- backend/handler/webauthn.go
Fixes that login errors are shadowed by audit log creation errors.
> fix: return shadowed error

- backend/crypto/passcode_test.go
- backend/go.mod
- backend/go.sum
- backend/handler/passcode_test.go
- backend/test/config.go
- backend/test/fixtures/passcode/emails.yaml
- backend/test/fixtures/passcode/primary_emails.yaml
- backend/test/fixtures/passcode/users.yaml
- backend/test/suite.go
Passcode handler test now uses the test suite.
Closes #621
> test: improve passcode handler tests

- backend/cmd/user/import.go
Add an option to the user import command to use a url to point to the file.
Example:
```shell
hanko user import -u https://example.com/path/to/file
```
The `-i` flag and the `-u` flag are mutually exclusive, but one has to be set.
> feat: add option to use a url to the user import file

- backend/cmd/user/import.go
Check of correct status code is wrong.
> fix: fix user import via url

- frontend/elements/package.json
- frontend/examples/angular/package.json
- frontend/examples/nextjs/package.json
- frontend/examples/react/package.json
- frontend/examples/svelte/package.json
- frontend/examples/vue/package.json
- frontend/frontend-sdk/package.json
- frontend/package-lock.json
> Version bump 0.8.1

- frontend/elements/package.json
- frontend/examples/angular/package.json
- frontend/examples/nextjs/package.json
- frontend/examples/react/package.json
- frontend/examples/svelte/package.json
- frontend/examples/vue/package.json
- frontend/frontend-sdk/package.json
- frontend/package-lock.json
> chore: frontend version bump

- docs/docs/guides/backend.mdx
> Fix: remove note

- frontend/elements/README.md
- frontend/elements/example.css
- frontend/elements/src/_preset.sass
- frontend/elements/src/components/link/styles.sass
- frontend/elements/src/components/spacer/styles.sass
Changing the max-width  and adding padding around in the container can bring a nicer UI for the user's first impression of the Hanko components
> hanko-auth component styled slightly different

- backend/flowpilot/action_input.go
- backend/flowpilot/builder.go
- backend/flowpilot/context.go
- backend/flowpilot/context_action_exec.go
- backend/flowpilot/context_flow.go
- backend/flowpilot/flow.go
- backend/flowpilot/input.go
- backend/flowpilot/payload.go
- backend/flowpilot/response.go
- backend/flowpilot/stash.go
- Variables for state names renamed
- Comments added / improved
- And more...
> flowpilot refactoring

- backend/flow_api_test/actions.go
- backend/flow_api_test/flow.go
- backend/flowpilot/builder.go
- backend/flowpilot/context.go
- backend/flowpilot/context_action_exec.go
- backend/flowpilot/flow.go
Adds the possibility to add hook actions to be executed before a certain state.
> feat: introduce hook actions

- backend/flow_api_test/actions.go
- backend/flow_api_test/flow.go
- backend/flowpilot/builder.go
- backend/flowpilot/builder_subflow.go
- backend/flowpilot/context.go
- backend/flowpilot/context_action_exec.go
- backend/flowpilot/context_flow.go
- backend/flowpilot/db.go
- backend/flowpilot/flow.go
- backend/persistence/migrations/20230810173315_create_flows.up.fizz
- backend/persistence/models/flow.go
- backend/persistence/models/flowdb.go
- "endState / flow completed" functionality removed
- `FixedStates()` replaced with `ErrorState()` and `InitialState()`
-  after state hook actions introduced
- further refactoring
> feat: flow builder interface improved

- README.md
- docs/docs/intro.md
I have changed the name of Twitter to X in all the documentation of this repository.
This repository has so many stars and forks. Wouldn't it be the best to be updated with the latest?
Everyone must be well aware by now that the legal name of Twitter has been formally changed to X. Therefore, I have updated the README files and other documentation and corrected the name to X.
Kindly review the PR and merge it. Suggest changes (if any)
> Updated the name of Twitter in all the docs

- backend/cmd/user/format.go
- backend/json_schema/hanko.config.json
- backend/json_schema/hanko.user_import.json
Fix json schema for the user import.
Fixed struct tags, so that the schema is generated correct now.
Closes #1198
> fix: fix user-import json schema

- backend/flow_api/flow/passcode/action_resend_passcode.go
- backend/flow_api/flow/passcode/action_verify_passcode.go
- backend/flow_api/flow/passcode/flow.go
- backend/flow_api/flow/passcode/hook_send_passcode.go
- backend/flow_api/flow/shared/errors.go
- backend/flow_api/flow/shared/flow.go
- backend/flow_api/handler.go
- backend/flow_api/services/passcode.go
- backend/flowpilot/context.go
- backend/flowpilot/context_action_exec.go
- backend/handler/public_router.go
- backend/rate_limiter/rate_limiter.go
- Passcode functionality improved, so it behaves like in the old API.
- The flowpilot `HookExecutionContext` now offers two new methods: `GetFlowError` and `SetFlowError`.
> chore: passcode functionality improved

- backend/README.md
* add chapter about data structure of a webhook event
* add info that you need to implement an endpoint on your application
* add info that a webhook JWT can be decoded with the JWK created in an earlier chapter
> chore(webhooks): improve webhook docs

- README.md
Roadmap updated to reflect latest developments
> Roadmap updated

- backend/handler/public_router.go
- backend/handler/thirdparty.go
- backend/thirdparty/linking.go
* add user.create event trigger to thirdparty signup
* add user.update when an email is added to an identity
* add email.create when email is created
Closes: #1361
> feat(webhooks): add webhooks trigger to thirdparty auth

- backend/flow_api/flow/passkey_onboarding/action_webauthn_verify_attestation_response.go
- backend/flow_api/flow/profile/action_password_set.go
- backend/flow_api/flow/profile/hook_get_profile_data.go
- backend/flowpilot/input.go
This PR includes the following fixes and adjustments:
- nil pointer exception while validating min and max length fixed
- change public_key input type to json
- add the actual username to the related input field to be displayed in the UI
- add a value for max_length (72) to the password input
> Flow api adjustments

- frontend/elements/src/contexts/AppProvider.tsx
- frontend/elements/src/pages/LoginInitPage.tsx
- frontend/elements/src/pages/RegistrationInitPage.tsx
- frontend/frontend-sdk/src/lib/flow-api/types/action.ts
- frontend/frontend-sdk/src/lib/flow-api/types/input.ts
- frontend/frontend-sdk/src/lib/flow-api/types/payload.ts
- frontend/frontend-sdk/src/lib/flow-api/types/state-handling.ts
> Feat add conditional UI

- frontend/elements/src/contexts/AppProvider.tsx
- frontend/elements/src/pages/LoginInitPage.tsx
- frontend/elements/src/pages/RegistrationInitPage.tsx
- frontend/frontend-sdk/src/lib/flow-api/Flow.ts
- frontend/frontend-sdk/src/lib/flow-api/types/action.ts
- frontend/frontend-sdk/src/lib/flow-api/types/input.ts
- frontend/frontend-sdk/src/lib/flow-api/types/payload.ts
- frontend/frontend-sdk/src/lib/flow-api/types/state-handling.ts
Add the social login button to the login and sign up pages.
> feat: add thirdparty login to elements

- backend/config/config.go
- backend/config/config_default.go
- backend/flow_api/flow/credential_usage/action_password_login.go
- backend/flow_api/flow/credential_usage/action_resend_passcode.go
- backend/flow_api/flow/credential_usage/hook_send_passcode.go
- backend/flow_api/flow/flows.go
- backend/flow_api/flow/login/action_continue_with_login_identifier.go
- backend/flow_api/flow/profile/action_email_create.go
- backend/flow_api/flow/profile/action_webauthn_credential_create.go
- backend/flow_api/flow/shared/action_exchange_token.go
- backend/flow_api/flow/shared/const_stash_paths.go
- backend/flow_api/flow/shared/flow.go
- backend/flow_api/flow/user_details/action_set_email.go
- backend/flow_api/handler.go
- backend/handler/public_router.go
- backend/rate_limiter/rate_limiter.go
Fix some some issues related to the new config.
> Flow api fix config usage

- backend/config/config.go
Add tags to all config parameters.
> fix: add tags to all config parameters

- backend/flow_api/flow/credential_usage/hook_send_passcode.go
- backend/flow_api/flow/login/hook_create_email.go
- backend/flow_api/flow/profile/action_account_delete.go
- backend/flow_api/flow/profile/action_email_create.go
- backend/flow_api/flow/profile/action_email_delete.go
- backend/flow_api/flow/profile/action_email_set_primary.go
- backend/flow_api/flow/registration/hook_create_user.go
- backend/flow_api/services/email.go
- backend/flow_api/services/passcode.go
- backend/handler/public_router.go
- Adds webhooks to the flow-api
> chore: add webhooks to flow-api

- frontend/elements/package.json
- frontend/examples/angular/package.json
- frontend/examples/fresh/islands/Login.tsx
- frontend/examples/fresh/islands/LogoutButton.tsx
- frontend/examples/fresh/islands/Profile.tsx
- frontend/examples/nextjs/package.json
- frontend/examples/react/package.json
- frontend/examples/svelte/package.json
- frontend/examples/vue/package.json
- frontend/frontend-sdk/package.json
- frontend/package-lock.json
Updates the frontend versions to v1.0.1.
> chore: update versions to 1.0.1

- frontend/elements/package.json
- frontend/examples/angular/package.json
- frontend/examples/fresh/islands/Login.tsx
- frontend/examples/fresh/islands/LogoutButton.tsx
- frontend/examples/fresh/islands/Profile.tsx
- frontend/examples/nextjs/package.json
- frontend/examples/react/package.json
- frontend/examples/svelte/package.json
- frontend/examples/vue/package.json
- frontend/frontend-sdk/package.json
- frontend/package-lock.json
Updates the frontend versions to v1.0.2.
> chore: update versions to 1.0.2

- backend/flow_api/flow/credential_onboarding/action_skip_method_chooser.go
- backend/flow_api/flow/credential_onboarding/action_skip_passkey.go
- backend/flow_api/flow/credential_onboarding/action_skip_password.go
- backend/flow_api/flow/credential_onboarding/action_webauthn_verify_attestation_response.go
- backend/flow_api/flow/credential_usage/action_verify_passcode.go
- backend/flow_api/flow/flows.go
- backend/flow_api/flow/login/hook_schedule_onboarding_states.go
- backend/flow_api/flow/mfa_creation/skip_mfa.go
- backend/flow_api/flow/registration/action_register_login_identifier.go
- backend/flow_api/flow/registration/hook_schedule_mfa_creation_states.go
- backend/flowpilot/context.go
- backend/flowpilot/context_flow.go
- backend/flowpilot/stash.go
Make small adjustments to unify the login flow and registration flow, ensuring both use the same code and business logic for managing MFA onboarding.
> chore: adjust login flow

- backend/handler/webhook.go
> chore(webhooks): update webhook.go

- oss.gg/5_follow_on_linkedin.md
- oss.gg/6_follow_on_x.md
Oss.gg Side quests for twitter and Linkedin follows.
Screenshots attached:
> ossgg: Linkedin and X sidequests

- frontend/elements/package.json
- frontend/examples/angular/package.json
- frontend/examples/fresh/islands/Login.tsx
- frontend/examples/fresh/islands/LogoutButton.tsx
- frontend/examples/fresh/islands/Profile.tsx
- frontend/examples/nextjs/package.json
- frontend/examples/react/package.json
- frontend/examples/svelte/package.json
- frontend/examples/vue/package.json
- frontend/frontend-sdk/package.json
- frontend/package-lock.json
Updates the frontend versions to v1.1.0.
> chore: update versions to 1.1.0

- frontend/elements/src/i18n/bn.ts
- frontend/elements/src/i18n/de.ts
- frontend/elements/src/i18n/en.ts
- frontend/elements/src/i18n/fr.ts
- frontend/elements/src/i18n/it.ts
- frontend/elements/src/i18n/pt-BR.ts
- frontend/elements/src/i18n/zh.ts
- frontend/elements/src/pages/CreateSecurityKeyPage.tsx
Change texts regarding security creation to be more consistent across the flows and to be more precise.
> Text changes for security key labels

- frontend/elements/src/components/accordion/ManageAuthAppDropdown.tsx
- frontend/elements/src/pages/CreateSecurityKeyPage.tsx
- frontend/elements/src/pages/LoginMethodChooser.tsx
- frontend/elements/src/pages/ProfilePage.tsx
- frontend/elements/src/pages/RegisterPasskeyPage.tsx
- Loading spinner alignent fixed on serval pages
- Fixed that the authenticator app deletion link is shown, when it's not allowed to delete the app
> Fix: UI issues

- backend/dto/admin/user.go
- backend/flow_api/flow/credential_usage/action_password_recovery.go
- backend/flow_api/flow/flows.go
- backend/flow_api/flow/login/hook_trigger_login_webhook.go
- backend/flow_api/flow/profile/action_account_delete.go
- backend/flow_api/flow/profile/action_password_update.go
- backend/webhooks/events/events.go
- backend/webhooks/utils/webhook.go
This PR introduces new webhook events and enhances event payloads by including user-related metadata (IP address & User-Agent
- **Added IP address & User-Agent to user DTO** (`backend/dto/admin/user.go`)  
- New optional fields: `IPAddress`, `UserAgent`  
- Methods: `SetIPAddress()`, `SetUserAgent()`  
- **Changed webhook trigger logic** (`backend/webhooks/utils/webhook.go`)  
- Enriches webhook payloads with `User-Agent` and `IP address` before sending.  
- **New webhook event: `UserPasswordChange`** (`backend/webhooks/events/events.go`)  
- Used in password update & recovery flows.  
- **New webhook event: `UserLogin`** (`backend/webhooks/events/events.go`)  
- Used when the login flow succeeds.  
- **Added `TriggerLoginWebhook` flow action** …
> Feat: New Webhook Events & User Metadata Enhancements

- frontend/elements/package.json
- frontend/examples/angular/package.json
- frontend/examples/fresh/islands/Login.tsx
- frontend/examples/fresh/islands/LogoutButton.tsx
- frontend/examples/fresh/islands/Profile.tsx
- frontend/examples/nextjs/package.json
- frontend/examples/react/package.json
- frontend/examples/svelte/package.json
- frontend/examples/vue/package.json
- frontend/frontend-sdk/package.json
- frontend/package-lock.json
> chore: update versions to 1.4.0

- frontend/elements/package.json
- frontend/examples/angular/package.json
- frontend/examples/fresh/islands/Login.tsx
- frontend/examples/fresh/islands/LogoutButton.tsx
- frontend/examples/fresh/islands/Profile.tsx
- frontend/examples/nextjs/package.json
- frontend/examples/react/package.json
- frontend/examples/svelte/package.json
- frontend/examples/vue/package.json
- frontend/frontend-sdk/package.json
- frontend/package-lock.json
Update frontend-sdk and elements version to 1.5.0
> chore: update versions to 1.5.0

- frontend/elements/package.json
- frontend/examples/angular/package.json
- frontend/examples/fresh/islands/Login.tsx
- frontend/examples/fresh/islands/LogoutButton.tsx
- frontend/examples/fresh/islands/Profile.tsx
- frontend/examples/nextjs/package.json
- frontend/examples/react/package.json
- frontend/examples/svelte/package.json
- frontend/examples/vue/package.json
- frontend/frontend-sdk/package.json
- frontend/package-lock.json
Update frontend-sdk and elements version to 1.5.1
> chore: update versions to 1.5.1

- frontend/elements/src/Elements.tsx
- frontend/frontend-sdk/src/Hanko.ts
- frontend/frontend-sdk/src/lib/SessionStorage.ts
- frontend/frontend-sdk/src/lib/client/HttpClient.ts
- frontend/frontend-sdk/src/lib/client/UserClient.ts
- frontend/frontend-sdk/src/lib/events/Relay.ts
- frontend/frontend-sdk/tests/lib/client/EmailClient.spec.ts
- frontend/frontend-sdk/tests/lib/client/EnterpriseClient.spec.ts
- frontend/frontend-sdk/tests/lib/client/HttpClient.spec.ts
- frontend/frontend-sdk/tests/lib/client/ThirdPartyClient.spec.ts
- frontend/frontend-sdk/tests/lib/client/TokenClient.spec.ts
- frontend/frontend-sdk/tests/lib/client/UserClient.spec.ts
Add an option where the session token can be stored. Either as a cookie or in the sessionStorage.
> feat: add session token location

- frontend/elements/package.json
- frontend/examples/angular/package.json
- frontend/examples/fresh/islands/Login.tsx
- frontend/examples/fresh/islands/LogoutButton.tsx
- frontend/examples/fresh/islands/Profile.tsx
- frontend/examples/nextjs/package.json
- frontend/examples/react/package.json
- frontend/examples/svelte/package.json
- frontend/examples/vue/package.json
- frontend/frontend-sdk/package.json
- frontend/package-lock.json
Update frontend-sdk and elements version to 1.5.2
> chore: update versions to 1.5.2

- frontend/elements/README.md
- frontend/frontend-sdk/README.md
- Improved comments for session validation, token retrieval, user profile, logout, and events.
- Streamlined event docs for `onSessionCreated`, `onSessionExpired`, `onUserLoggedOut`, `onUserDeleted`.
- Updated session/user client examples to use current SDK methods.
- Added TypeScript docs in `frontend-sdk/README.md` for `getUser()`, `validateSession()`, `getSessionToken()`, `logout()`.
- Removed deprecated code (e.g., `hanko.session.get()`).
> chore: update/improve the sdk and elements readme files

- frontend/elements/package.json
- frontend/examples/angular/package.json
- frontend/examples/fresh/islands/Login.tsx
- frontend/examples/fresh/islands/LogoutButton.tsx
- frontend/examples/fresh/islands/Profile.tsx
- frontend/examples/nextjs/package.json
- frontend/examples/react/package.json
- frontend/examples/svelte/package.json
- frontend/examples/vue/package.json
- frontend/frontend-sdk/package.json
- frontend/package-lock.json
Increase version numbers to `2.0.0`.
> chore: increase version numbers

- frontend/frontend-sdk/src/Hanko.ts
- frontend/frontend-sdk/src/lib/client/HttpClient.ts
Ge the session token from cookie per default.
> fix: get session token from cookie per default

- frontend/frontend-sdk/README.md
- Updated the description of the `username` field in the user profile
- Corrected the example user profile output to align with the updated username structure
> fix: wrong username object in readme
